baseURL = 'https://example.org/'
languageCode = 'ko'
title = '분노의 기록'
theme = "LoveIt"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "light"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt NEW | 0.2.0 date format
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "My cool site111111111"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "descriptiondescription"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

  # LoveIt NEW | 0.2.0 App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "화난 블로그"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "/images/goose.jpeg"
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
  # Author config
  [params.author]
    name = "cptppung"
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
  [params.header.title]
    # URL of the LOGO
    logo = "/images/goose.jpeg"
    # title name
    name = "분노의 기록"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
    typeit = false
  [params.page]
    [params.page.comment]
      enable = true
    [params.page.comment.giscus]
      # You can refer to the official documentation of giscus to use the following configuration.
      enable = true
      repo = "cptppung/cptppung.github.io"
      repoId = "R_kgDORr7WRA"
      category = "General"
      categoryId = "DIC_kwDORr7WRM4C5Nmu"
      # automatically adapt the current theme i18n configuration when empty
      lang = "ko"
      mapping = "pathname"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom"
      lazyLoading = false
      lightTheme = "light"
      darkTheme = "dark"
    [params.page.share]
      enable = false
  [params.analytics]
    # LoveIt DELETED | 0.3.1
    enable = true
    # Google Analytics
    [params.analytics.google]
      # id = "G-RY8RJSNY84"
      id = "GTM-5TWMTQQ8"
      # LoveIt NEW | 0.3.1 whether to respect the browser’s “do not track” setting
      respectDoNotTrack = false

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
  # Home page profile
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/goose.jpeg"
    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    # title = "title!!!!!!!"
    # subtitle shown in home page (HTML format is supported)
    subtitle = "하나씩 천천히..."
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false
